{{ range $secret := .Values.clusterSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ $secret.name }}
  {{- with $secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector: {}
  externalSecretName: {{ $secret.externalSecretName }}
  refreshTime:  {{ $secret.refreshTime }}
  {{- with $secret.externalSecretMetadata }}
  externalSecretMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $secret.externalSecretSpec }}
  externalSecretSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}