{{ range $secretStore := .Values.secretStores }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $secretStore.name }}
  {{- with $secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $secretStore.provider }}
  provider:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}