apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.serviceAccount.namespace }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}